name: Hashnode Blog Posts
on:
  schedule:
    # Runs every day at 04:00
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.ewers-peters.de/rss.xml"
          max_post_count: 10
          template: "$newline - $randomEmoji(ðŸ’¯,ðŸ”¥,ðŸ’«,ðŸš€,ðŸŒ®) [$title]($url)"
          commit_message: "recent posts section updated"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
